# Generated by Django 4.2.5 on 2023-09-24 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("public_id", models.CharField(max_length=30, unique=True)),
                ("track_id", models.CharField(max_length=30, unique=True)),
                ("current_element_id", models.CharField(max_length=30)),
                ("starting_element_id", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="TrackElementGroupAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("element_id", models.CharField(db_index=True, max_length=30)),
                ("date_finished", models.DateTimeField(auto_now_add=True)),
                ("answer", models.TextField()),
                ("hint_used", models.BooleanField(default=False)),
                ("score", models.IntegerField(null=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rally.group"
                    ),
                ),
            ],
        ),
    ]
