# Generated by Django 4.2.5 on 2023-09-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rally", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="track_id",
            field=models.CharField(max_length=30),
        ),
    ]
