name: publish

on:
  push:
    branches:
      - 'master'
jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build_push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/wiomoc/campus-rally:latest
      - name: Deploy on dev infra
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: serv03.wiomoc.de
          key: ${{ secrets.SSH_KEY }}
          username: ubuntu
          script: |
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker stop campus-rally || true
            docker rm campus-rally || true
            ghcr.io/wiomoc/campus-rally@${{ steps.docker_build_push.outputs.digest }}
            docker run -d --name campus-rally \
              --restart=unless-stopped \
              -v /home/ubuntu/rallydata:/app/data \
              -l "traefik.enable=true" \
              -l "traefik.http.routers.rally.entrypoints=websecure" \
              -l "traefik.http.routers.rally.rule=Host(\`rally.wiomoc.de\`)" \
              -l "traefik.http.routers.rally.tls.certresolver=mainresolver" \
              -l "traefik.http.services.rally.loadbalancer.server.port=8080" \
              -l "traefik.http.routers.rally.service=rally" \
              -l "traefik.docker.network=web" \
              -e HOSTNAME=rally.wiomoc.de \
              --network=web \
              ghcr.io/wiomoc/campus-rally@${{ steps.docker_build_push.outputs.digest }}
            docker image prune -a --filter "until=24h" -f